#!/bin/sh
provision_list=${1:-default}

if [ "${provision_list}" == "-l" ]; then
  echo "available provision tags:"
  grep -E "^\S.*:" provision.yaml| sed s/://
  exit 0
fi

# remove existing bolt inventory from litmus
rm -rf spec/fixtures/litmus_inventory.yaml

# distribute opn-cli config from dist files
cp spec/fixtures/acceptance/opn-cli/conf.yaml.dist spec/fixtures/acceptance/opn-cli/conf.yaml
cp spec/fixtures/acceptance/opn-cli/ca.pem.dist spec/fixtures/acceptance/opn-cli/ca.pem

# setup opnsense with vagrant
vagrant up

# setup test docker containers
pdk bundle install
pdk bundle exec rake "litmus:provision_list[${provision_list}]"

# fix puppet agent install - use docker tmp path
sed -i '' '
/shell-command: bash -lc/a\
\ \ \ \ \ \ \ \ tmpdir: "\/\"
' spec/fixtures/litmus_inventory.yaml

pdk bundle exec rake "litmus:install_agent[puppet7]"
pdk bundle exec rake litmus:install_module
