#!/bin/bash
version=${1:-}

if [ -z "${version}" ]; then
  echo "Please provide the version to release as argument to the script"
  echo "$0 1.0.0"
  exit 1
fi
pdk release prep --version=${version} --force
